# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: WildFireUpdate
# label used for menu selection
label: WildFireUpdate
description: This Skillet configures aggressive WildFire 1 minute updates with download and install immediately action.

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Configure
    - BreenSkillets

# ---------------------------------------------------------------------
# end of preamble section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: WildFireUpdate
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule
    file: WildFireUpdate.xml
# ---------------------------------------------------------------------
# end of snippets section
